### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Deroin** [puppets-epic-show-theatre/puppet-curator#10]
Dependencies currently state that `puppetlabs/stdlib` and `puppetlabs/concat` both need to be below `5.0.0`. Also only `Ubuntu 14.04` is officially supported.
I'm running this on `Ubuntu 20.04` with `puppetlabs/stdlib` on version `6.5.0` and `puppetlabs/concat` on `6.3.0` without issues. But sadly I cannot import this via `Puppetfile` as I don't meed the module dependency requirements.

Would it be okay to update the dependencies accordingly?

**Comment by TuningYourCode** [comment]
Hi,
yeah, we forked the module to update it. Currently we are in the progress to get the current version as good as possible to run with pdk.
We hope to be able to publish the first version in the following days - so stay tuned and if you like provide some PR if you have any changes you want to have in this package.

**Comment by TuningYourCode** [comment]
We created a new release which includes newer versions of the dependencies and also more recent ubuntu versions.

**Comment by Deroin** [comment]
Thanks for the new version. Seems to be working on the first look.

On our fork we also fixed some deprecations in manifests/init.pp where `validate_bool` and `validate_string` are used. We replaced those with `validate_legacy`. But as it is just a deprecation warning it's not a real issue and thus we can just ignore it.

**Comment by TuningYourCode** [comment]
yeah, we removed them too and introduced some basic data types. I published them now as 4.0.1 as it could possible break something as most variables didn't had any type checking before. If you have more refined data types feel free to open an PR :)
